# Generated by Django 3.1.4 on 2022-06-25 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=30, verbose_name='Compañia')),
                ('nit', models.IntegerField(blank=True, null=True, verbose_name='Nit')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Codigo')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
                ('bills_products', models.ManyToManyField(blank=True, to='products.Products')),
                ('client_id', models.ForeignKey(help_text='Ingrese Cliente', on_delete=django.db.models.deletion.PROTECT, to='clients.clients', verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'db_table': 'bills',
            },
        ),
    ]
