# Generated by Django 3.1.4 on 2022-06-25 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.IntegerField(blank=True, null=True, verbose_name='Documento')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('useremail', models.ForeignKey(help_text='Ingrese Usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'clients',
            },
        ),
    ]
