# Generated by Django 3.1.4 on 2022-06-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Nombre Producto')),
                ('descripcion', models.CharField(blank=True, max_length=256, verbose_name='Descripcion')),
                ('atributo4', models.CharField(blank=True, max_length=64, verbose_name='Atributo 4')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
            },
        ),
    ]
